@setfilename cl-docweaver.info

@dircategory Common Lisp
@direntry
* CL-DocWeaver: (cl-docweaver). Common Lisp documentation weaver.
@end direntry

@include ../common-lisp.texi

@c Setup cl-docweaver


@node Top
@top Top
@cindex docweaver
@cindex cl-docweaver

@menu
* Introduction::
* API::
* Index::
@end menu

@node Introduction
@chapter Introduction
@anchor{introduction}

@node API
@chapter API
@anchor{api}

@majorheading DOCWEAVER

@cldefun {DOCWEAVER, DEF-WEAVER-COMMAND-HANDLER, (command-name args (&key backend) &body body)}


@endcldefun

@cldefun {DOCWEAVER, PROCESS-WEAVER-COMMAND, (backend command args stream)}


@endcldefun

@cldefun {DOCWEAVER, WEAVE-FILE, (file output-file &rest options &key backend modules command-prefix
 (parse-docstrings t))}

Weaves documentation source in @var{FILE} and writes the result to @var{OUTPUT-FILE}.

Arguments:
 @code{-} @var{BACKEND} specify the documentation tool that is being used (@var{:texinfo}, @var{:markdown}, etc.).
@code{-} @var{MODULES} is the list of @var{modules} (or ASDF system names) that need to be loaded to be able to read definition descriptions.
@code{-} @var{COMMAND-PREFIX} is the character to use as prefix for commands. The character `at` is the default.
@code{-} PARSE-DOCSTRINGS: if @var{T}, then docstings are parsed and highlighted and references to code from it created.

@endcldefun



@node Index
@chapter Index

@printindex cp
@printindex vr
@printindex fn

@bye
