@setfilename cl-docweaver.info

@dircategory Common Lisp
@direntry
* CL-DocWeaver: (cl-docweaver). Common Lisp documentation weaver.
@end direntry

@include ../common-lisp.texi

@c Setup cl-docweaver
(@setup :command-prefix #\$ :backend :texinfo)

@node Top
@top Top
@cindex docweaver
@cindex cl-docweaver

@menu
* Introduction::
* API::
* Index::
@end menu

@node Introduction
@chapter Introduction
@anchor{introduction}

@node API
@chapter API
@anchor{api}

($clpackage "docweaver")

@node Index
@chapter Index

@printindex cp
@printindex vr
@printindex fn

@bye
