@setfilename cl-docweaver.info

@dircategory Common Lisp
@direntry
* CL-DocWeaver: (cl-docweaver). Common Lisp documentation weaver.
@end direntry

@include ../common-lisp.texi

@c Setup cl-docweaver


@node Top
@top Top
@cindex webinfo

@menu
* Introduction::
* API::
@end menu

@node Introduction
@chapter Introduction
@anchor{introduction}

@node API
@chapter API
@anchor{api}

@majorheading DOCWEAVER

@cldefun {DOCWEAVER, DEF-WEAVER-COMMAND-HANDLER, (command-name args (&key backend) &body body)}

@endcldefun

@cldefun {DOCWEAVER, PROCESS-WEAVER-COMMAND, (backend command args stream)}

@endcldefun

@cldefun {DOCWEAVER, WEAVE-FILE, (file output-file &rest options &key backend modules command-prefix
 parse-docstrings)}
Weaves documentation source in FILE and writes the result to OUTPUT-FILE.

Arguments:
 - BACKEND specify the documentation tool that is being used (:texinfo, :markdown, etc.).
- MODULES is the list of modules (or ASDF system names) that need to be loaded to be able to read definition descriptions.
- COMMAND-PREFIX is the character to use as prefix for commands. The character `at` is the default.
- PARSE-DOCSTRINGS: if T, then docstings are parsed and highlighted and references to code from it created.

@endcldefun



@bye
