@setfilename cl-docweaver.info

@dircategory Common Lisp
@direntry
* CL-DocWeaver: (cl-docweaver). Common Lisp documentation weaver.
@end direntry

@include ../common-lisp.texi

@c Setup cl-docweaver
(@setup :command-prefix #\$ :docsystem :texinfo)

@node Top
@top Top
@cindex docweaver
@cindex cl-docweaver

@menu
* Introduction::
* Installation::
* Usage::
* API::
* Index::
@end menu

@node Introduction
@chapter Introduction
@anchor{introduction}

CL-DOCWEAVER is a document weaver for Common Lisp.

Documentation for a Lisp project can be written using (potentially) any tool choosen by the user (like Texinfo, Markdown, etc). Then, Common Lisp definitions are referenced and embedded from the documentation source using some commands.

CL-DOCWEAVER is easy to extend to support different documentation tools.

Texinfo and Markdown are the ones with best support at this moment.

@node Installation
@chapter Installation
@anchor{installation}


@node Usage
@chapter Usage
@anchor{usage}

Invoke ($clref docweaver:weave-file :function)  on your documentation source files.

@node API
@chapter API
@anchor{api}

($clpackage "docweaver")

@node Index
@chapter Index

@printindex cp
@printindex vr
@printindex fn

@bye
